### ISSUE TITLE
`gpt.transl_style` 无效

### ISSUE THREAD

**Issue by thiliapr** [xd2333/GalTransl#122]
# 问题
最近，我在研究`SakuraLLM`的代码时，注意到`gpt.transl_style`配置项似乎并未发挥其预期的作用。

### `sampleProject/config.inc.yaml`
- 大约在文件的第30行附近：
  ```yaml
  gpt.transl_dropout: 0 # (Sakura/Galtransl-v1)（实验性）丢弃翻译结果末尾的n行，可能会提高上下文准确性。[0-2]
  # GalTransl
  gpt.transl_style: "流畅" # (GalTransl-v1)翻译风格选择[流畅/文艺]
  
  # 插件选择，插件介绍可在启动程序后选择showplugs查看
  ```

### `GalTransl/Backend/SakuraTranslate.py`
- 第63行附近：
  ```python3
  # transl_style 配置处理
  if val := config.getKey("gpt.transl_style"):
      self.transl_style = val
  else:
      self.transl_style = "流畅"
  ```

- 第108行附近：
  ```python3
  self.chatbot.update_proxy(
      self.proxyProvider.getProxy().addr if self.proxyProvider else None  # type: ignore
  )
  self.transl_style = "auto"
  self._current_style = "precies"  # 注意这里可能是拼写错误，预期可能是 "precise"
  ```

## 详细描述
经过仔细分析，尽管在`GalTransl/Backend/SakuraTranslate.py`的第63行左右正确地从配置文件中读取并设置了`transl_style`的值，但随后在第108行，该值被无条件地覆盖为`"auto"`。这意味着，无论`config.yaml`文件中如何配置`gpt.transl_style`，其实际效果都将被忽略，始终被设置为`"auto"`。

既然`transl_style`的值在运行时总是被覆盖，那么为何还要在配置文件中提供这一选项？
