### ISSUE TITLE
没有重翻NewBing拒绝翻译的句子

### ISSUE THREAD

**Issue by OPPO9008** [XD2333/GalTransl#16]
如题
设置部分
```
# 通用（杂项）设置
common:
  loggingLevel: info # 日志等级，可选 [debug/info/warning/error]
  retranslFail: True # 重翻NewBing拒绝翻译的句子。[True/False]
  multiThread: false # 多线程，[True/False]（暂不可用）
  gpt.streamOutputMode: true # 流式输出/打字机效果，开启方便观察过程，关闭方便观察结果。[True/False]
  gpt.numPerRequestTranslate: 9 # 单次翻译句子数量，不建议太大
  gpt.enableProofRead: False # (NewBing/GPT4)是否开启译后校润。[True/False]
  gpt.numPerRequestProofRead: 7 # (NewBing/GPT4)单次校润句子数量，不建议修改
  gpt.degradeBackend: false # (GPT3.5/4 官方API)是否将 GPT4 的key用于 GPT3.5 的请求。[True/False]
  gpt.restoreContextMode: True # (GPT3.5/4 官方API)重启自动恢复上下文。[True/False]
  gpt.fullContextMode: True # (GPT3.5/4 官方API)尽可能多的保留前文，翻译逻辑性更好，消耗token约翻4倍。[True/False]
  gpt.lineBreaksImprovementMode: false # (GPT3.5)换行符改善模式，减少丢换行符情况，但可能导致循环重试。[True/False]
  gpt.recordConfidence: true # (GPT4)记录确信度、存疑句，GPT4官方API关掉可节约token。[True/False]
  gpt.forceNewBingHs: false # (NewBing)强制NewBing翻译hs，导致速度变得很慢且可能更容易被ban号。[True/False]
```

部分没有重新翻译的翻译缓存

```
    {
        "index": 49,
        "name": "",
        "pre_jp": "女の子が少し動くと、ワンピースの脇から見えている乳房の先に時々乳首が見えたりして。",
        "post_jp": "女の子が少し動くと、ワンピースの脇から見えている乳房の先に時々乳首が見えたりして。",
        "pre_zh": "Failed translation",
        "proofread_zh": "Failed translation",
        "trans_by": "NewBing(Failed)",
        "proofread_by": "NewBing(Failed)",
        "post_zh_preview": "Failed translation"
    },
    {
        "index": 50,
        "name": "",
        "pre_jp": "可愛らしいピンク色の突起は、思わず手を伸ばして触りたくなる程魅惑的だ。",
        "post_jp": "可愛らしいピンク色の突起は、思わず手を伸ばして触りたくなる程魅惑的だ。",
        "pre_zh": "Failed translation",
        "proofread_zh": "Failed translation",
        "trans_by": "NewBing(Failed)",
        "proofread_by": "NewBing(Failed)",
        "post_zh_preview": "Failed translation"
    },
    {
        "index": 51,
        "name": "女の子",
        "pre_jp": "「あ〜……あつい〜……」",
        "post_jp": "あ〜……あつい〜……",
        "pre_zh": "Failed translation",
        "proofread_zh": "Failed translation",
        "problem": "比日文长1.7倍",
        "trans_by": "NewBing(Failed)",
        "proofread_by": "NewBing(Failed)",
        "post_zh_preview": "「Failed translation」"
    },
    {
        "index": 52,
        "name": "",
        "pre_jp": "そう言ってワンピースの胸元をパタパタさせたりすると、ますますその下にある可愛らしいオッパイがハッキリと俺の目に映った。",
        "post_jp": "そう言ってワンピースの胸元をパタパタさせたりすると、ますますその下にある可愛らしいオッパイがハッキリと俺の目に映った。",
        "pre_zh": "Failed translation",
        "proofread_zh": "Failed translation",
        "trans_by": "NewBing(Failed)",
        "proofread_by": "NewBing(Failed)",
        "post_zh_preview": "Failed translation"
    },
    {
        "index": 53,
        "name": "",
        "pre_jp": "そのサイズは完全に手のひらサイズでプリンとしていて触り心地が良さそうだ。",
        "post_jp": "そのサイズは完全に手のひらサイズでプリンとしていて触り心地が良さそうだ。",
        "pre_zh": "Failed translation",
        "proofread_zh": "Failed translation",
        "trans_by": "NewBing(Failed)",
        "proofread_by": "NewBing(Failed)",
        "post_zh_preview": "Failed translation"
    },
    {
        "index": 54,
        "name": "",
        "pre_jp": "そして、その可愛い乳房の先にある乳首は、プックリと膨らんでいてキレイなピンク色をしていた。",
        "post_jp": "そして、その可愛い乳房の先にある乳首は、プックリと膨らんでいてキレイなピンク色をしていた。",
        "pre_zh": "Failed translation",
        "proofread_zh": "Failed translation",
        "trans_by": "NewBing(Failed)",
        "proofread_by": "NewBing(Failed)",
        "post_zh_preview": "Failed translation"
    },
```
